### PR TITLE
Ci maintenance

### PR DESCRIPTION
**Pull request by abelsromero**
Thank you for opening a pull request and contributing to AsciidoctorJ PDF!

Please take a bit of time giving some details about your pull request:

## Kind of change

[ ] Bug fix
[ ] New non-breaking feature
[ ] New breaking feature
[ ] Documentation update
[x] Build improvement

## Description

What is the goal of this pull request?

Maintenance of the CI pipelines and build.

How does it achieve that?

* Adds Java17 support (gradle also was required for this)
* Bumps test dependencies to latests
* Bumps Asciidoctorj and asciidoctorj-diagram to latests
* Adds Windows build to CI pipeline
* Replace deprecated 'de.marcphilipp.nexus-publish' gradle plugin by 'nexus-publish'

Are there any alternative ways to implement this?

Not that I know of.

Are there any implications of this pull request? Anything a user must know?

I am afraid the Gradle bump may break something in the release, but I did not see anything suspicious.
But is this PR is OK, we could align with https://github.com/asciidoctor/asciidoctor-pdf/releases/tag/v1.6.1 and make a release to test it. Some local testing I did and upstream pipeline work nicely.

## Issue

If this PR fixes an open issue, please add a line of the form:

Fixes #Issue 

## Release notes

Please add a corresponding entry to the file CHANGELOG.adoc

### CODE REVIEW

**Comment by abelsromero** [comment]
About the removal of Groovy test, I had to do it due to an issue in which Groovy seems to translate new File(str) to new File(str, str) :man_shrugging: 
Since there was only 1 test, and it fixes the problem I went ahead, it also simplifies the overall build.

**Comment by abelsromero** [comment]
@robertpanzer any comments? :cat2:   . Btw I am keeping commits for review, let me know if you preffer me to squash manually.

**Comment by robertpanzer** [comment]
Sorry for responding late. 
I'll try this out tomorrow.

**Comment by robertpanzer** [comment]
Somehow it seems like with this PR I can no longer publish to Sonatype.
With current main I see these publishing tasks:
```
Publishing tasks
----------------
generateMetadataFileForMavenAsciidoctorJPdfPublication - Generates the Gradle metadata file for publication 'mavenAsciidoctorJPdf'.
generatePomFileForMavenAsciidoctorJPdfPublication - Generates the Maven POM file for publication 'mavenAsciidoctorJPdf'.
publish - Publishes all publications produced by this project.
publishAllPublicationsToLocalRepository - Publishes all Maven publications produced by this project to the local repository.
publishAllPublicationsToSonatypeRepository - Publishes all Maven publications produced by this project to the sonatype repository.
publishMavenAsciidoctorJPdfPublicationToLocalRepository - Publishes Maven publication 'mavenAsciidoctorJPdf' to Maven repository 'local'.
publishMavenAsciidoctorJPdfPublicationToMavenLocal - Publishes Maven publication 'mavenAsciidoctorJPdf' to the local Maven repository.
publishMavenAsciidoctorJPdfPublicationToSonatypeRepository - Publishes Maven publication 'mavenAsciidoctorJPdf' to Maven repository 'sonatype'.
publishToMavenLocal - Publishes all Maven publications produced by this project to the local Maven cache.
publishToSonatype - Publishes all Maven publications produced by this project to the 'sonatype' Nexus repository.
```

With this PR I only see this:
```
Publishing tasks
----------------
generateMetadataFileForMavenAsciidoctorJPdfPublication - Generates the Gradle metadata file for publication 'mavenAsciidoctorJPdf'.
generatePomFileForMavenAsciidoctorJPdfPublication - Generates the Maven POM file for publication 'mavenAsciidoctorJPdf'.
publish - Publishes all publications produced by this project.
publishAllPublicationsToLocalRepository - Publishes all Maven publications produced by this project to the local repository.
publishMavenAsciidoctorJPdfPublicationToLocalRepository - Publishes Maven publication 'mavenAsciidoctorJPdf' to Maven repository 'local'.
publishMavenAsciidoctorJPdfPublicationToMavenLocal - Publishes Maven publication 'mavenAsciidoctorJPdf' to the local Maven repository.
publishToMavenLocal - Publishes all Maven publications produced by this project to the local Maven cache.
```

Might there be any property missing on my side?

**Comment by abelsromero** [comment]
> Somehow it seems like with this PR I can no longer publish to Sonatype.

Applied same config as Asciidoctorj; added `io.github.gradle-nexus.publish-plugin` and removed 'io.codearte.nexus-staging'. And it seems to be fine now, there are new tasks `releaseSonatypeStagingRepository` but that's consistent with what AsciidoctorJ shows. I assume the release will be the same now requiring `sonatypeUsername`, `sonatypePassword` properties.

I am tempted to test it with my Sonatype credentials (the ones I use for maven-plugin), but I am not sure if it will also close the release or will be remain in staging. We wouldn't want to make an accidental release :sweat_smile: Can you confirm?

**Pull request merged**
